# Generated by Django 5.2.6 on 2025-10-07 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desp', '0002_alter_despuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDesp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Sugerido (R$)')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço do Despachante',
                'verbose_name_plural': 'Serviços do Despachante',
                'ordering': ['nome'],
            },
        ),
    ]
