# Generated by Django 5.2.6 on 2025-10-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desp', '0003_servicedesp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceDesp',
            new_name='ListarServiceDesp',
        ),
    ]
