# Generated by Django 5.2.6 on 2025-10-07 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desp', '0004_rename_servicedesp_listarservicedesp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ult_atualiz', models.DateTimeField(default=django.utils.timezone.now)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to=settings.AUTH_USER_MODEL, verbose_name='Despachante')),
            ],
            options={
                'verbose_name': 'Serviço do Despachante',
                'verbose_name_plural': 'Serviços do Despachante',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Documento')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='desp.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Documento Necessário',
                'verbose_name_plural': 'Documentos Necessários',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='ListarServiceDesp',
        ),
    ]
