# Generated by Django 5.2.6 on 2025-10-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desp', '0005_servico_documento_delete_listarservicedesp'),
    ]

    operations = [
        migrations.AddField(
            model_name='despuser',
            name='data_expiracao_crdd',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiração CRDD'),
        ),
        migrations.AddField(
            model_name='despuser',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='despuser',
            name='registro_crdd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro CRDD'),
        ),
        migrations.AddField(
            model_name='despuser',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='despuser',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone Pessoal'),
        ),
    ]
