# Generated by Django 5.2.6 on 2025-10-08 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desp', '0006_despuser_data_expiracao_crdd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('despachante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Despachante')),
                ('telefone_comercial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comercial')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço/Logradouro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
    ]
